# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

WORKDIR /app

COPY /package.json /package-lock.json ./
RUN npm install --production --ignore-scripts

COPY ./

CMD ["node", "index.js"]
