# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package descriptors
COPY .json/package.json .json/package-lock.json .json/tsconfig.json ./

# Copy source code
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Default command for stdio MCP server
CMD ["node", "dist/index.js"]
